# Maps each key to its expected Python type(s).
# Nested dicts indicate a sub-section where each leaf maps to a type.
# Lists and special constraints are validated separately in _loader._validate.
_SCHEMA: dict = {
    "physics": {
        "gravity_ratio": (int, float),
        "repel_ratio": (int, float),
        "k_attract": (int, float),
        "soft_core_radius": (int, float),
        "max_step": (int, float),
        "F_max": (int, float),
        "focus": list,
        "initial_temperature": (int, float),
        "cooling_factor": (int, float),
        "min_temperature": (int, float),
        "k_edge": (int, float),
        "edge_rest_length": (int, float),
        "repulsion_cutoff": (int, float),
        "bh_threshold": int,
        "bh_theta": (int, float),
        "mutation_reheat_factor": (int, float),
        "cpu_sparse_threshold": int,
    },
    "simulation": {
        "node_count": int,
        "weight_min": (int, float),
        "weight_max": (int, float),
        "spawn_distance": (int, float),
        "inner_radius_fraction": (int, float),
        "outer_radius_fraction": (int, float),
        "dims": int,
        "max_degree": int,
        "use_gpu": bool,
        "layout_noise": (int, float),
        "gpu_memory_pool_gb": (int, float),
    },
    "tick": {
        "dt": (int, float),
        "equilibrium_threshold": (int, float),
        "interval_ms": int,
        "render_every": int,
        "physics_substeps": int,
        "cuda_device": int,
        "stats_interval": (int, float),
        "headless_max_ticks": int,
    },
    "render": {
        "camera_elev": (int, float),
        "camera_azim": (int, float),
        "view_range": (int, float),
        "camera_distance": (int, float),
        "title": str,
        "size_scale": (int, float),
        "node_size_min": (int, float),
        "node_size_max": (int, float),
        "weight_to_size": (int, float),
    },
    "ui": {
        "window_title": str,
        "geometry": str,
        "button_padx": int,
        "button_pady": int,
    },
    "velocimetry": {
        "enabled": bool,
        "output_path": str,
        "save_csv": bool,
        "save_npz": bool,
        "plot_on_convergence": bool,
        "max_frames": int,
    },
    # Nested: each value is itself a dict of {field: type}.
    "sliders": {
        "gravity_ratio": {"min": (int, float), "max": (int, float), "step": (int, float)},
        "repel_ratio":   {"min": (int, float), "max": (int, float), "step": (int, float)},
        "k_edge":        {"min": (int, float), "max": (int, float), "step": (int, float)},
    },
}
